### ISSUE TITLE
error on stream

### ISSUE THREAD

**Issue by jvargh1971** [citymapper/rds-logs-archiver#2]
hi- any thoughts on below error on line 'response = rds._endpoint.http_session.send(request.prepare(), stream=True)'?
`send() got an unexpected keyword argument 'stream'`

**Comment by slai** [comment]
I can take a look this weekend, but in case you weren't aware, AWS RDS now has [native support for shipping some logs to Cloudwatch Logs](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Concepts.PostgreSQL.html#USER_LogAccess.PostgreSQL.PublishtoCloudWatchLogs), which you can then [ship to S3](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/S3Export.html) from there too.

I think this is only useful if you're using a database/version that doesn't support log shipping to Cloudwatch, want to ship unsupported logs, or if you want to bypass Cloudwatch for some reason, e.g. cost.

**Comment by jvargh1971** [comment]
@slai Appreciate the response. Aware of the CW approach by RDS DBs, but as you mentioned cost is a prohibitive factor on shipping to CW first and the use case requires S3 as final destination. This solution however is unique in the streaming direct to S3 approach, without having to download first. Below are versions used
`boto3==1.17.12
botocore==1.20.12
botostubs==0.14.1.17.12
certifi==2020.12.5
chardet==4.0.0
idna==2.10
jmespath==0.10.0
python-dateutil==2.8.1
requests==2.25.1
s3transfer==0.3.4
six==1.15.0
urllib3==1.26.3
`

**Comment by slai** [comment]
I've updated this to Python 3.8 and fixed the bug reported here. I ran a quick test and it seems to work. 

See https://github.com/slai/rds-logs-archiver for the new code (I no longer have access to this repo so I've forked it). Feel free to open issues over there; I should be notified properly.

**Comment by jvargh1971** [comment]
Looks good for closure. Thanks @slai
